### ISSUE TITLE
VERY important bugs found

### ISSUE THREAD

**Issue by AlejandroColomar** [rwestlund/freesweep#3]
- When playing, if I resize the terminal to be smaller than the board, segmentation fault is produced.
 - If I start the game in a terminal smaller than the numbers I introduce for the size, the system hangs really bad.  I had to use tty3 to init 6. (Killing -9 freesweep didn't help).

**Comment by AlejandroColomar** [comment]
Using the version packaged with Debian stretch (stable), which is 0.90-3+b1

**Comment by apoleon** [comment]
I have just packaged version 1.0.1 for Debian and I can still reproduce this issue. However on my Debian stable system an error message is printed and I don't experience that the system hangs.

	***Segmentation Fault detected. Cleaning up....

**Comment by AlejandroColomar** [comment]
I did it again:

In a gnome terminal:
$ su
# apt-get purge freesweep
# apt-get install freesweep
# exit
$ freesweep
resize the terminal as small as I can, and... gnome is unrecoverable.
kill -9 freesweep or the gnome terminal, or even the gnome shell doesn't work.  Just init 6.

**Comment by reinerh** [comment]
That's the backtrace I get when making the terminal window really small:
```
#0  malloc_consolidate (av=av@entry=0x7fb286601c40 <main_arena>) at malloc.c:4439
#1  0x00007fb2864cc0bd in _int_malloc (av=av@entry=0x7fb286601c40 <main_arena>, bytes=bytes@entry=224) at malloc.c:4112
#2  0x00007fb2864cd64c in __GI___libc_malloc (bytes=224) at malloc.c:3057
#3  0x00007fb2866552e8 in wresize () from /lib/x86_64-linux-gnu/libncurses.so.6
#4  0x00007fb2866549b3 in ?? () from /lib/x86_64-linux-gnu/libncurses.so.6
#5  0x00007fb286654cb7 in resize_term_sp () from /lib/x86_64-linux-gnu/libncurses.so.6
#6  0x00007fb286654d68 in resizeterm_sp () from /lib/x86_64-linux-gnu/libncurses.so.6
#7  0x00007fb28661a810 in _nc_update_screensize () from /lib/x86_64-linux-gnu/libtinfo.so.6
#8  0x00007fb286644402 in ?? () from /lib/x86_64-linux-gnu/libncurses.so.6
#9  0x00007fb286644957 in wgetch () from /lib/x86_64-linux-gnu/libncurses.so.6
#10 0x000056245d2f4678 in GetInput (Game=0x56245dd34260) at play.c:28
#11 0x000056245d2ee736 in main (argc=<optimized out>, argv=<optimized out>) at main.c:102

```
